### PR TITLE
Typescript and v2.0.0

### PR DESCRIPTION
**Pull request by evantahler**
**This is a breaking change.**  
This version of `ah-sequelize-plugin` will only work with `Actionhero >= v21`

---
The updated Readme for this version can be read here https://github.com/actionhero/ah-sequelize-plugin/blob/typescript/README.md
---

## Use sequelize-typescript
* Include the wonderful [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript) package.
* Model files are now declared as simple classes with tags, ie:
```ts
// from `src/models/Users.ts`
import * as bcrypt from "bcrypt";
import {
  Model,
  Table,
  Column,
  AllowNull,
  IsEmail,
  BeforeCreate,
  HasMany
} from "sequelize-typescript";
import * as uuid from "uuid/v4";
import { Post } from "./Post";

@Table({ tableName: "users", paranoid: true })
export class User extends Model<User> {
  saltRounds = 10;

  @Column({ primaryKey: true })
  guid: string;

  @AllowNull(false)
  @Column
  firstName: string;

  @AllowNull(false)
  @Column
  lastName: string;

  @AllowNull(false)
  @IsEmail
  @Column
  email: string;

  @Column
  passwordHash: string;

  @HasMany(() => Post)
  posts: Post[];

  @BeforeCreate
  static generateGuid(instance) {
    if (!instance.guid) {
      instance.guid = uuid();
    }
  }

  async updatePassword(password: string) {
    this.passwordHash = await bcrypt.hash(password, this.saltRounds);
    await this.save();
  }

  async checkPassword(password: string) {
    if (!this.passwordHash) {
      throw new Error("password not set for this team member");
    }

    const match = await bcrypt.compare(password, this.passwordHash);
    return match;
  }
}
```

## Migrations
* We now auto-migrate by default
* Migrations now use Actionhero's logger

## Testing
* move from Mocha to Jest
* test with Postgres rather than sqlite for a more realistic test 
* simplify and modernize tests
* remove the plugin test, as those are out of scope for this plugin (you can provide multiple model and migration files in the seqeulize config) 

## Misc
* Update the license in the project to APACHE-2.0 from MIT to match Actionhero

--- 

## Usage notes:

* File Setup:
  * create `src/models` for your model files.  They are to be Capitalized.
  * create `src/migrations` for your migration files. 
    * Migrations should remain as `*.js` files rather than `*.ts` files.  Typescript files will run just fine, but the default Uzmug storage engine places file names into the database table.  This means if you try to run your project in both TS and JS "modes", you will get conflicting migrations. 
* You will need to enable `experimentalDecorators` and `emitDecoratorMetadata` in your `tsconfig.json` in your actionhero project
* There is no more `api.models`, and now that your models will be regular ES6 Classes, you can directly require them.

While we ship with a complex example, a minimal config for `ah-sequelize-plugin` now looks like: 
```ts
export const DEFAULT = {
  sequelize: config => {
    return {
      autoMigrate: true,
      loadFixtures: false,
      logging: false,
      dialect: dialect,
      port: parseInt(port),
      database: database,
      host: host,
      username: username,
      password: password,
      models: [path.join(__dirname, "..", "models")],
      migrations: [path.join(__dirname, "..", "migrations")]
    };
  }
};

// for the seqeilize CLI tool
module.exports.development = DEFAULT.sequelize({
  env: "development",
  process: { env: "development" }
});

module.exports.staging = DEFAULT.sequelize({
  env: "staging",
  process: { env: "staging" }
});

module.exports.production = DEFAULT.sequelize({
  env: "production",
  process: { env: "production" }
});

```

### CODE REVIEW

**Comment by evantahler** [comment]
@inian Please review this version!

**Comment by evantahler** [comment]
closes https://github.com/actionhero/ah-sequelize-plugin/pull/80

**Comment by inian** [comment]
@evantahler should [this line](https://github.com/actionhero/ah-sequelize-plugin/blob/0ac922cf33bfe0af4241b85cbc83a53631341ed6/src/initializers/sequelize.ts#L28) be config.sequelize.migrationsDir

**Comment by inian** [comment]
Also, I think `addModels` needs to be called before we can start using the models. https://github.com/RobinBuschmann/sequelize-typescript#configuration

**Comment by evantahler** [comment]
Hi @inian! Thanks for the review:
* I've renamed `migrationsDir` to `migrations` in the config.  I did this to more closely match the options that Uzmug was expecting 
* I don't think you need to call `addModels` if you pass the array of paths to `models` in the ts-sequelize constructor, which we do here https://github.com/actionhero/ah-sequelize-plugin/blob/0ac922cf33bfe0af4241b85cbc83a53631341ed6/src/initializers/sequelize.ts#L18... and the tests confirm that things are working https://github.com/actionhero/ah-sequelize-plugin/blob/0ac922cf33bfe0af4241b85cbc83a53631341ed6/__tests__/integration.ts#L41-L54

**Comment by inian** [comment]
Hey @evantahler both of the issues were cos I was setting modelsDir and migrationsDir. I changed them back to models and migrations and things work as expected. Please publish a new version to npm when its ready.

**Comment by evantahler** [comment]
Published

**Pull request merged**
